version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: edu3_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: web3_course_platform
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: